[2017-03-02 15:54:09,143] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-02 15:54:09,158] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-02 15:54:39,191] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-33. (kafka.log.LogCleaner)
[2017-03-02 15:54:39,191] INFO Cleaner 0: Building offset map for __consumer_offsets-33... (kafka.log.LogCleaner)
[2017-03-02 15:54:39,222] INFO Cleaner 0: Building offset map for log __consumer_offsets-33 for 1 segments in offset range [0, 1147). (kafka.log.LogCleaner)
[2017-03-02 15:54:39,237] INFO Cleaner 0: Offset map for log __consumer_offsets-33 complete. (kafka.log.LogCleaner)
[2017-03-02 15:54:39,253] INFO Cleaner 0: Cleaning log __consumer_offsets-33 (cleaning prior to Wed Mar 01 19:29:58 IST 2017, discarding tombstones prior to Thu Jan 01 05:30:00 IST 1970)... (kafka.log.LogCleaner)
[2017-03-02 15:54:39,269] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-33 (largest timestamp Wed Mar 01 19:29:56 IST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-02 15:54:39,300] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-33. (kafka.log.LogCleaner)
[2017-03-02 15:54:39,331] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:327)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:329)
	at kafka.log.Log.replaceSegments(Log.scala:992)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:425)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:364)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at kafka.log.Cleaner.clean(LogCleaner.scala:363)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:239)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:218)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-33\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-33\00000000000000000000.log.swap: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:670)
	at kafka.log.FileMessageSet.renameTo(FileMessageSet.scala:427)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-33\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-33\00000000000000000000.log.swap: The process cannot access the file because it is being used by another process.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:667)
		... 11 more
[2017-03-02 15:54:39,331] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
